spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notis_app?serverTimezone=America/Argentina/Cordoba
    username: dev
    password: userdev1295
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: eb1eece6b19a9c
    password: ed814f343a2257

jwt:
  expirationInMillis: 3600000
  secretKey: notis1295